snakedir: "."

global:
  read_folder: "benchmark/sra_data/data/reads/PRJEB2869/"
  out_dir: "benchmark/sra_data/out/Sung_2012_PRJEB2869/isling"
  R1_suffix: "_1.fastq.gz"
  R2_suffix: "_2.fastq.gz"
  read1-adapt: ""
  read2-adapt: ""

  dedup: False  
  dedup-subs: 2
  
  split: 1
  
  merge: False
  trim: False
  
  host_name: "GRCm38"
  host_fasta: "benchmark/sra_data/data/references/mm10_no_alt_analysis_set_ENCODE.fasta"
  virus_name: "HBVs"
  virus_fasta: "benchmark/sra_data/data/references/SRP023539_HBV.fa"
  align-cpus: 5

  mean-frag-len: "estimate"
  clip-cutoff: 20
  cigar-tol: 3
  alt-edit-dist-thresh: 3
    
  merge-method: 'common'
  min-n-merge: 1

  mapq-thresh: 20

  generate-report: False

all:
  filter:
    - "True"

