Nelson_2019_PRJNA485509:
   read_directory: "../../data/reads/PRJNA485509/"
   out_directory: "../../out/"
   R1_suffix: "_1.fastq.gz"
   R2_suffix: "_2.fastq.gz"
   read1-adapt: "CTGTCTCTTATACACATCT"
   read2-adapt: "CTGTCTCTTATACACATCT"
   
   # analysis
   analysis_host: # if running vifi, there must be a matching key in analysis_hosts under vifi_params
       "GRCm38" : "../../data/references/mm10_no_alt_analysis_set_ENCODE.fasta"
   analysis_virus:
       "nelson_aavs" :  "../../data/references/Nelson_2016_AAVs.fa"
   
   #run polyidus?
   # https://github.com/hoffmangroup/polyidus
   # note container contains my fork: https://github.com/szsctt/polyidus
   polyidus_params:
     trim: False
     aligner: "bowtie2"
      
   # run vifi - can't, only works on human data
#   vifi_params:
#     trim: True
#     host_info:
#       human: # fasta will be used from general analysis_hosts
#         mappability: "../vifi-test/data_repo/GRCh38/hg38full_k35_noMM.mappability.bedgraph"
#         mappability_exclude: "../data/references/GRCh38/ENCFF356LFX.bed"
#         genes: "../data/references/GRCh38/hg38.gencode.v35.annotation.genes.gff3"
#         exons: "../data/references/GRCh38/hg38.gencode.v35.annotation.exons.gff3"
#         oncogenes: "../data/references/GRCh38/hg38.gencode.v35.annotation.genes.gff3"
#         centromeres: "../data/references/GRCh38/centromeres.bed"
#         conserved_regions: "../data/references/GRCh38/exclude.cnvnator_100bp.GRCh38.20170403.bed"
#         segdup: "../data/references/GRCh38/genomicSuperDups.bed"
     
   # run verse
   # https://bioinfo.uth.edu/VirusFinder/VirusFinder-manual.pdf?csrt=2093584511125027598
#   verse_params:
#     detection_mode: sensitive
#     flank_region_size: 4000
#     sensitivity_level: 1
#     min_contig_length: 300
#     blastn_evalue_thrd: 0.05
#     similarity_thrd: 0.8
#     chop_read_length: 25
#     minIdentity: 80     
#     trim: False
 
   seeksv_params:
     trim: False
     dedup: False
     
   vseq_toolkit_params:
     qua: 20
     lenPer: 50
     mode: 'default'
     vecVecFusion: 'true'
     stringencyVec: 'medium'
     UMthresholdVec: 0.95
     minMapSpanVec: 20
     distVecVec: 10
     opVecVec: 5
     idenVecVec: 95
     stringencyVecGen: 'medium'
     UMthresholdVecGen: 0.95
     minMapSpanVecGen: 20
     distVecGen: 10
     opVecGen: 5
     idenVecGen: 95
     clusterRange: 3
     host_table:
       GRCm38_p6: "$VSeqToolkit/testDir/testReferenceIndex/refSeqUCSCTablehg38.txt"
       
Nelson_2019_PRJNA485509_vseq_novecvecfusion:
   read_directory: "../../data/reads/PRJNA485509/"
   out_directory: "../../out/"
   R1_suffix: "_1.fastq.gz"
   R2_suffix: "_2.fastq.gz"
   read1-adapt: "CTGTCTCTTATACACATCT"
   read2-adapt: "CTGTCTCTTATACACATCT"

   # analysis
   analysis_host: # if running vifi, there must be a matching key in analysis_hosts under vifi_params
       "GRCm38_p6" : "../../data/references/GRCm38_p6.fa"
   analysis_virus:
       "nelson_aavs" :  "../../data/references/Nelson_2016_AAVs.fa"


   vseq_toolkit_params:
     qua: 20
     lenPer: 50
     mode: 'default'
     vecVecFusion: 'false'
     stringencyVec: 'medium'
     UMthresholdVec: 0.95
     minMapSpanVec: 20
     distVecVec: 10
     opVecVec: 5
     idenVecVec: 95
     stringencyVecGen: 'medium'
     UMthresholdVecGen: 0.95
     minMapSpanVecGen: 20
     distVecGen: 10
     opVecGen: 5
     idenVecGen: 95
     clusterRange: 3
     host_table:
       GRCm38_p6: "$VSeqToolkit/testDir/testReferenceIndex/refSeqUCSCTablehg38.txt"
