global:
   read_directory: "../../data/reads/PRJNA606282/"
   out_directory: "../../out/Ngyuen_2020_PRJNA606282"
   R1_suffix: "_1.fastq.gz"
   R2_suffix: "_2.fastq.gz"
   read1-adapt: "AGATCGGAAGAGCACACGTCTGAACTCCAGTCA"
   read2-adapt: "AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT"
   
   # analysis
   analysis_host: # if running vifi, there must be a matching key in analysis_hosts under vifi_params
       camFam3 : "../../data/references/Canis_lupus_familiaris.CanFam3.1.dna.toplevel.fa"

   
   #run polyidus?
   # https://github.com/hoffmangroup/polyidus
   # note container contains my fork: https://github.com/szsctt/polyidus
   polyidus_params:
     trim: False
     aligner: "bowtie2"
      
#   # run vifi - can't because isn't human data
#   vifi_params:
#     trim: False
#     host_info:
#       GRCh37: # fasta will be used from general analysis_hosts
#         mappability: "../../../Release/GRCh37/wgEncodeDukeMapabilityUniqueness35bp_sorted.bedGraph"
#         mappability_exclude: "../../../Release/GRCh37/GRCh37_wgMapabilityExcludable.bed"
#         genes: "../../../Release/GRCh37/human_hg19_september_2011/Genes_July_2010_hg19.gff"
#         exons: "../../../Release/GRCh37/human_hg19_september_2011/Exon-Intron_July_2010_hg19.gff"
#         oncogenes: "../../../Release/GRCh37/cancer/oncogenes/Census_oncomerge.gff"
#         centromeres: "../../../Release/GRCh37/human_g1k_v37_centromere.bed"
#         conserved_regions: "../../../Release/GRCh37/conserved.gain5.bed"
#         segdup: "../../../Release/GRCh37/annotations/hg19GenomicSuperDup.tab"

     
   # run verse
   # https://bioinfo.uth.edu/VirusFinder/VirusFinder-manual.pdf?csrt=2093584511125027598
#   verse_params:
#     detection_mode: sensitive
#     flank_region_size: 4000
#     sensitivity_level: 1
#     min_contig_length: 300
#     blastn_evalue_thrd: 0.05
#     similarity_thrd: 0.8
#     chop_read_length: 25
#     minIdentity: 80     
#     trim: False

   seeksv_params:
     trim: False
     dedup: False
 
   vseq_toolkit_params:
     qua: 20
     lenPer: 50
     mode: 'default'
     vecVecFusion: 'false'
     stringencyVec: 'medium'
     UMthresholdVec: 0.95
     minMapSpanVec: 20
     distVecVec: 10
     opVecVec: 5
     idenVecVec: 95
     stringencyVecGen: 'medium'
     UMthresholdVecGen: 0.95
     minMapSpanVecGen: 20
     distVecGen: 10
     opVecGen: 5
     idenVecGen: 95
     clusterRange: 3
     host_table:
       camFam3: "../../data/references/dog_genes_vseq_toolkit.txt"


#Lau_2014_SRP023539_one_HBV_hg19:
#   analysis_virus:
#       "HBV" :  "/scratch1/sco305/intvi_external-data/data/references/SRP023539_one_HBV.fa"
   

all_vectors:
  analysis_virus: 
    Ngyuen_vectors: "../../data/references/Ngyuen_vectors.fasta"
  samples:
    - SRR11074331

two_chain:
  analysis_virus: 
    Ngyuen_two_chain: "../../data/references/Ngyuen_dual_vectors.fasta"
  samples:
    - SRR11074332
    - SRR11074333
    - SRR11074334
    - SRR11074344
    - SRR11074345
    - SRR11074346
    - SRR11074347
    - SRR11074348
    - SRR11074349

one_chain:
  analysis_virus: 
    Ngyuen_single_chain: "../../data/references/Ngyuen_single_vector.fasta"
  samples:
    - SRR11074335
    - SRR11074336
    - SRR11074337
    - SRR11074341
    - SRR11074342
    - SRR11074343
    - SRR11074339
    - SRR11074350
    - SRR11074351


